services:
  db:
    image: postgres:16
    env_file:
        - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - wuzapi-network
      
networks:
  wuzapi-network:
    driver: bridge

volumes:
  db_data: